service_token="******************************************"
provider_type ="gcp"
project_id = "***********************************"
region= "us-central1"
zone = "us-central1-c"
project_name = "**********************************"